entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
    http:
      tls: {}  # Enable TLS for HTTPS

providers:
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

api:
  dashboard: true
  insecure: true  # Enable dashboard on port 8080 (for debugging)

log:
  level: DEBUG  # Enable debug logging for troubleshooting
accessLog: {}